version: '3'

services:
  email_service:
    build:
      context: .
      dockerfile: Dockerfile
    image: email_service_test:dev
    ports:
      - 9090:8080
      - 9091:8081
    container_name: kcc_email_service